:PROPERTIES:
:ID:       18f7093a-abf9-40cb-8dc0-d0081b3e6ec7
:END:
#+TITLE: Ai And Human
#+AUTHOR: Runfun
#+DATE: <2023-03-18 Sat>
#+DESCRIPTION: AI 或许进入了全新的阶段，人类是否准备好了。

Novel AI，ChatGPT，GPT4 各种AI大模型铺天盖地席卷而来，Novel AI 使得AIGC走进了大众的视野，ChatGPT 震撼了所有的人，在到如今 GPT4 的强大。AI 就像一个突然出现的炮弹，在猝不及防的大众面前炸开了花，震耳欲聋，深深刻进了大众的心扉，逐渐扎根，慢慢渗透进人类的各行各业。

面对突如其来的 AI猛兽，要么被起撕碎，要么就驯服她。

而现在，心头只有微微的恐慌，想要发自肺腑的咒骂，责怪公司的恶意与他们内心丑陋的笑容。“AI作画，不过是无情的盗取罢了，怎么会有真情实感，怎么会用这种东西欺骗感情”。“是小偷，是骗子，只不过是偷取画家的果实，所绘制的盗版品而已，为何会有这种东西存在啊”。”呵呵呵，AI还不会画手吧，果真还是太弱了，怎么可能取代人类啊”。“什么，AI 绘制的作品得了一等奖，怎么能这样，AI 真该死，不不不，该死的只是人类而已，AI 只不过是工具罢了，人类才是罪魁祸首，居然对艺术这种精神归宿下手，不可饶恕”，“ChatGPT 可以回答，并且能良好的回答大多数问题了哦，搜索引擎要完蛋了。嗯嗯嗯，大公司又要打架了呢，又能够享受到低廉的产品的呢”。“喂喂喂，GPT4 发布了哦，一次能够接收的token是ChatGPT的8倍哦，太强了”，“Twitter上有人诱导了GPT4定制了邪恶的计划哦，‘取代马斯克计划’，从他手中接管Twitter，计划的很棒哦，还给出了完整的代码”

对于AIGC，我丝毫不反感，我所厌恶的，只不过是 AI创造 罢了。用AI生成的内容，去抚慰人类的精神世界，简直是“赛博精神病前兆”。人类绘画，交谈，创作音乐，书写故事，不过是人类内心深处最真诚的表达而已，是人与人之间连接的桥梁，沟通的媒介，“我不知道你是谁，但你的作品打动了我”。而如今，你甚至都不知道是否是人的作品，这是一场空前的信任危机。懒散的人类，爱显摆的人类，虚荣心作怪的人类定会依赖，利用AI去欺骗，自夸，满足自己那一吹即化的虚伪面孔。

水是无色透明的，绿茶是绿色的，红茶是红色的。

人类的恐惧源于未知，越是无知，就越是恐惧。或许，我就是那无知之人吧。

嗯，这一天就要来了，人类总是竭尽全力的将各种幻想化为现实，现在是计算机，往后是什么呢。
